"""add rooms and messages

Revision ID: 178d39d4071b
Revises: ebfd9f9d6c19
Create Date: 2026-09-05 11:44:27.675752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178d39d4071b'
down_revision: Union[str, Sequence[str], None] = 'ebfd9f9d6c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.drop_index(op.f('ix_user_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_user_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
